package org.campagnelab.NYoSh.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.impl.query.QueryProviderBase;
import jetbrains.mps.generator.template.CreateRootRuleContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.baseLanguage.behavior.Classifier__BehaviorDescriptor;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.TemplateArgumentContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.generator.template.WeavingMappingRuleContext;
import java.util.Map;
import jetbrains.mps.generator.impl.query.ReductionRuleCondition;
import java.util.HashMap;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.impl.query.QueryKey;
import jetbrains.mps.generator.template.ReductionRuleQueryContext;
import jetbrains.mps.generator.impl.GenerationFailureException;
import jetbrains.mps.generator.impl.query.CreateRootCondition;
import jetbrains.mps.generator.impl.query.WeaveRuleCondition;
import jetbrains.mps.generator.impl.query.WeaveRuleQuery;
import jetbrains.mps.generator.impl.query.WeaveAnchorQuery;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.generator.template.WeavingAnchorContext;
import jetbrains.mps.generator.impl.query.SourceNodeQuery;
import jetbrains.mps.generator.impl.query.QueryKeyImpl;
import jetbrains.mps.generator.impl.query.SourceNodesQuery;
import java.util.Collection;
import jetbrains.mps.util.IterableUtil;
import jetbrains.mps.generator.impl.query.PropertyValueQuery;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.generator.impl.query.IfMacroCondition;
import jetbrains.mps.generator.impl.query.ReferenceTargetQuery;
import jetbrains.mps.generator.impl.query.CallArgumentQuery;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.smodel.SModelUtil_new;

@Generated
public class QueriesGenerated extends QueryProviderBase {
  public QueriesGenerated() {
    super(1);
  }
  public static boolean createRootRule_Condition_2010614965247312410(final CreateRootRuleContext _context) {
    // Create a dummy error management node if none was provided explicitly 
    return ListSequence.fromList(SModelOperations.roots(_context.getOriginalInputModel(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x7744411300250a44L, "org.campagnelab.NYoSh.structure.ErrorManagement"))).isEmpty();
  }
  public static boolean baseMappingRule_Condition_1428468137067871(final BaseMappingRuleContext _context) {
    if (ListSequence.fromList(SNodeOperations.getNodeDescendants(_context.getNode(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x5132f28e0e080L, "org.campagnelab.NYoSh.structure.IRequireExecuteCommandEnvironment"), false, new SAbstractConcept[]{})).isNotEmpty()) {
      if (ListSequence.fromList(SNodeOperations.getNodeDescendants(_context.getNode(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x71c4aa344c8b239cL, "org.campagnelab.NYoSh.structure.ExecuteCommand"), false, new SAbstractConcept[]{})).isEmpty()) {
        return true;
      }
    }
    return false;
  }
  public static boolean baseMappingRule_Condition_3999230645370603588(final BaseMappingRuleContext _context) {
    if (SNodeOperations.getParent(_context.getNode()) == null && ListSequence.fromList(SNodeOperations.getNodeDescendants(_context.getNode(), MetaAdapterFactory.getInterfaceConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x60cbcaafef4d643L, "org.campagnelab.NYoSh.structure.ISomeStepLoggingStatement"), false, new SAbstractConcept[]{})).isNotEmpty()) {
      if (ListSequence.fromList(SNodeOperations.getNodeDescendants(_context.getNode(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x60cbcaafef4d649L, "org.campagnelab.NYoSh.structure.StepsLoggerDeclared"), false, new SAbstractConcept[]{})).isEmpty()) {
        return true;
      }
    }
    return false;
  }
  public static boolean baseMappingRule_Condition_4907898740900732088(final BaseMappingRuleContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x5ee96c8d4eb2558fL, 0x5ee96c8d4eb25609L, "consumeStandardOutput"));
  }
  public static boolean baseMappingRule_Condition_4907898740900775119(final BaseMappingRuleContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x5ee96c8d4eb2558fL, 0x5ee96c8d4eb25609L, "consumeStandardOutput"));
  }
  public static boolean baseMappingRule_Condition_4907898740900909782(final BaseMappingRuleContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x5ee96c8d4eb2558fL, 0x5ee96c8d4eb2560bL, "consumeStandardError"));
  }
  public static boolean baseMappingRule_Condition_4907898740901038182(final BaseMappingRuleContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x5ee96c8d4eb2558fL, 0x5ee96c8d4eb2560bL, "consumeStandardError"));
  }
  public static boolean baseMappingRule_Condition_4907898740901275816(final BaseMappingRuleContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x5ee96c8d4eb2558fL, 0x5ee96c8d4eb25609L, "consumeStandardOutput"));
  }
  public static boolean baseMappingRule_Condition_7518874264088361664(final BaseMappingRuleContext _context) {
    return SNodeOperations.getParent(_context.getNode()) == null && ListSequence.fromList(SNodeOperations.getNodeDescendants(_context.getNode(), MetaAdapterFactory.getInterfaceConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x1be723a87fb27988L, "org.campagnelab.NYoSh.structure.ISomeErrorUsage"), false, new SAbstractConcept[]{})).isNotEmpty() && !(Sequence.fromIterable(Classifier__BehaviorDescriptor.staticFields_id4_LVZ3pBr7M.invoke(_context.getNode())).any(new IWhereFilter<SNode>() {
      public boolean accept(SNode f) {
        return SPropertyOperations.getString(f, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("errorManagement");
      }
    }));
  }
  public static boolean baseMappingRule_Condition_2010614965249460538(final BaseMappingRuleContext _context) {
    // Only report exceptions when error management is defined 
    return ListSequence.fromList(SModelOperations.roots(_context.getOriginalInputModel(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x7744411300250a44L, "org.campagnelab.NYoSh.structure.ErrorManagement"))).isNotEmpty();
  }
  public static boolean baseMappingRule_Condition_2010614965249549323(final BaseMappingRuleContext _context) {
    // Only report exceptions when error management is defined 
    return ListSequence.fromList(SModelOperations.roots(_context.getOriginalInputModel(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x7744411300250a44L, "org.campagnelab.NYoSh.structure.ErrorManagement"))).isNotEmpty();
  }
  public static boolean baseMappingRule_Condition_2010614965249905459(final BaseMappingRuleContext _context) {
    return ListSequence.fromList(SModelOperations.roots(_context.getOriginalInputModel(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x7744411300250a44L, "org.campagnelab.NYoSh.structure.ErrorManagement"))).isEmpty();
  }
  public static boolean baseMappingRule_Condition_2010614965249966423(final BaseMappingRuleContext _context) {
    return ListSequence.fromList(SModelOperations.roots(_context.getOriginalInputModel(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x7744411300250a44L, "org.campagnelab.NYoSh.structure.ErrorManagement"))).isEmpty();
  }
  public static Object propertyMacro_GetPropertyValue_7872582389600940400(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL, 0x10d34fa226eL, "alias"));
  }
  public static Object propertyMacro_GetPropertyValue_435930706556389111(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x60cbcaafef4d644L, 0x60cbcaafef4d645L, "description"));
  }
  public static Object propertyMacro_GetPropertyValue_435930706556389138(final PropertyMacroContext _context) {
    return _context.createUniqueName("success", _context.getNode());
  }
  public static Object propertyMacro_GetPropertyValue_435930706556389155(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x60cbcaafef4d644L, 0x60cbcaafef4d645L, "description"));
  }
  public static Object propertyMacro_GetPropertyValue_435930706556389162(final PropertyMacroContext _context) {
    return _context.createUniqueName("reason", _context.getNode());
  }
  public static Object propertyMacro_GetPropertyValue_5787209143228213122(final PropertyMacroContext _context) {
    return _context.createUniqueName("exception", SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfc092b6b77L, "jetbrains.mps.baseLanguage.structure.BlockStatement"), false, false));
  }
  public static Object propertyMacro_GetPropertyValue_9039864166930640540(final PropertyMacroContext _context) {
    return _context.createUniqueName(SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")), _context.getNode());
  }
  public static Object propertyMacro_GetPropertyValue_7507736014962008517(final PropertyMacroContext _context) {
    return _context.createUniqueName(SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")), _context.getNode());
  }
  public static Object propertyMacro_GetPropertyValue_9039864166930247303(final PropertyMacroContext _context) {
    return _context.createUniqueName(SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")), null);
  }
  public static Object propertyMacro_GetPropertyValue_7507736014961255884(final PropertyMacroContext _context) {
    return _context.createUniqueName(SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")), null);
  }
  public static Object propertyMacro_GetPropertyValue_731554740236414150(final PropertyMacroContext _context) {
    return "lastExitCode";
  }
  public static Object propertyMacro_GetPropertyValue_731554740236377473(final PropertyMacroContext _context) {
    return "lastExitCode";
  }
  public static Object referenceMacro_GetReferent_4927548581349126141(final ReferenceMacroContext _context) {
    if (SNodeOperations.isInstanceOf(_context.getNode(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x5ee96c8d4e8af6bcL, "org.campagnelab.NYoSh.structure.ChangeDirectory"))) {
      return "changeDirectory";
    }
    if (SNodeOperations.isInstanceOf(_context.getNode(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x3536540b1e1d20d8L, "org.campagnelab.NYoSh.structure.BashFragment"))) {
      return "appendBashFragment";
    }
    return (SNodeOperations.isInstanceOf(_context.getNode(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x712db2b017ad72bcL, "org.campagnelab.NYoSh.structure.GStringCommand")) ? "appendCommand" : "appendOperator");
  }
  public static Object referenceMacro_GetReferent_7414196263097490723(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.as(ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x71c4aa344c8b239cL, 0xbd2729caaea770bL, "commands"))).last(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x3536540b1e24b31aL, "org.campagnelab.NYoSh.structure.OutputFirstLineInVariable")), MetaAdapterFactory.getReferenceLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x3536540b1e24b31aL, 0x3536540b1e24b4c3L, "variable")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_9213669739149152106(final ReferenceMacroContext _context) {
    return "fail";
  }
  public static Object referenceMacro_GetReferent_9039864166929501704(final ReferenceMacroContext _context) {
    return "fail";
  }
  public static Object referenceMacro_GetReferent_9039864166928527666(final ReferenceMacroContext _context) {
    return "done";
  }
  public static Object referenceMacro_GetReferent_4907898740901298345(final ReferenceMacroContext _context) {
    if (SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x5ee96c8d4eb2558fL, 0x5ee96c8d4eb25609L, "consumeStandardOutput"))) {
      return "consumeStandardOutput";
    } else if (SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x5ee96c8d4eb2558fL, 0x5ee96c8d4eb2560bL, "consumeStandardError"))) {
      return "consumeStandardError";
    }
    return "undefinedMethod";
  }
  public static Object referenceMacro_GetReferent_7507736014961274012(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x6830d620bef9499aL, 0x6830d620bef9499bL, "handler")), "method_SuccessHandler");
  }
  public static Object referenceMacro_GetReferent_9039864166931916245(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x774441130037b248L, 0x774441130037b249L, "handler")), "method_ErrorHandler");
  }
  public static Object referenceMacro_GetReferent_9039864166931122960(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x774441130037b248L, 0x774441130037b249L, "handler")), "method_ErrorHandler"), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_7507736014961225987(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x6830d620bef9499aL, 0x6830d620bef9499bL, "handler")), "method_SuccessHandler");
  }
  public static boolean ifMacro_Condition_7414196263098247788(final IfMacroContext _context) {
    SNode lastCommand = ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x71c4aa344c8b239cL, 0xbd2729caaea770bL, "commands"))).last();
    return SNodeOperations.isInstanceOf(lastCommand, MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x3536540b1e24b31aL, "org.campagnelab.NYoSh.structure.OutputFirstLineInVariable")) && SPropertyOperations.getBoolean(SNodeOperations.as(lastCommand, MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x3536540b1e24b31aL, "org.campagnelab.NYoSh.structure.OutputFirstLineInVariable")), MetaAdapterFactory.getProperty(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x5ee96c8d4eb2558fL, 0x5ee96c8d4eb25609L, "consumeStandardOutput"));
  }
  public static boolean ifMacro_Condition_5949986731306071704(final IfMacroContext _context) {
    return Sequence.fromIterable(Classifier__BehaviorDescriptor.staticFields_id4_LVZ3pBr7M.invoke(SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c108ca66L, "jetbrains.mps.baseLanguage.structure.ClassConcept"), false, false))).any(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("exportedVariables");
      }
    });
  }
  public static boolean ifMacro_Condition_4325409482886268091(final IfMacroContext _context) {
    return !(SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x71c4aa344c8b239cL, 0x3c06f101f78b00ccL, "ignoreErrors")));
  }
  public static boolean ifMacro_Condition_7855977029128093197(final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x71c4aa344c8b239cL, 0x6d06097c38cf15e5L, "printExecutedToStdout"));
  }
  public static boolean ifMacro_Condition_9138295635397069272(final IfMacroContext _context) {
    SNode lastCommand = ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x71c4aa344c8b239cL, 0xbd2729caaea770bL, "commands"))).last();
    return SNodeOperations.isInstanceOf(lastCommand, MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x3536540b1e24b31aL, "org.campagnelab.NYoSh.structure.OutputFirstLineInVariable")) && SPropertyOperations.getBoolean(SNodeOperations.as(lastCommand, MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x3536540b1e24b31aL, "org.campagnelab.NYoSh.structure.OutputFirstLineInVariable")), MetaAdapterFactory.getProperty(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x5ee96c8d4eb2558fL, 0x5ee96c8d4eb25609L, "consumeStandardOutput"));
  }
  public static boolean ifMacro_Condition_435930706556389241(final IfMacroContext _context) {
    return ListSequence.fromList(SNodeOperations.getNodeAncestors(_context.getNode(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x60cbcaafef4d648L, "org.campagnelab.NYoSh.structure.StepMarker"), false)).isEmpty();
  }
  public static boolean ifMacro_Condition_2477885976697156505(final IfMacroContext _context) {
    return !(((Boolean) _context.getVariable("innerClass")));
  }
  public static SNode sourceNodeQuery_7872582389600940237(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x712db2b017ad72bcL, 0x712db2b017ad72dcL, "command"));
  }
  public static SNode sourceNodeQuery_6839116863307682695(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x5ee96c8d4e8af6bcL, 0x5ee96c8d4e8d4dbcL, "path"));
  }
  public static SNode sourceNodeQuery_3834344539456361046(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x60cbcaafef4d63fL, 0x3536540b1cc02ed8L, "message"));
  }
  public static SNode sourceNodeQuery_3834344539458185979(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x60cbcaafef4d63fL, 0x3536540b1cc8f8c2L, "statusCode"));
  }
  public static SNode sourceNodeQuery_435930706556388982(final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }
  public static SNode sourceNodeQuery_435930706556389034(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x60cbcaafef4d637L, 0x60cbcaafef4d638L, "expression"));
  }
  public static SNode sourceNodeQuery_3834344539456372649(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x60cbcaafef4d63fL, 0x3536540b1cc02ed8L, "message"));
  }
  public static SNode sourceNodeQuery_435930706556389179(final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }
  public static SNode sourceNodeQuery_3834344539457451313(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x60cbcaafef4d63fL, 0x3536540b1cc02ed8L, "message"));
  }
  public static SNode sourceNodeQuery_3834344539457522265(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x60cbcaafef4d63fL, 0x3536540b1cc8f8c2L, "statusCode"));
  }
  public static SNode sourceNodeQuery_4907898740900748877(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x712db2b017ad696dL, "org.campagnelab.NYoSh.structure.ConsumeCommandOutputWithStream")), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x712db2b017ad696dL, 0x712db2b017ad725cL, "streamExpression")), MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L, 0x108bbd29b4aL, "body"));
  }
  public static SNode sourceNodeQuery_4927548581349126362(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x712db2b017bf4cf0L, 0x712db2b017bf4cf2L, "readerExpression")), MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L, 0x108bbd29b4aL, "body"));
  }
  public static SNode sourceNodeQuery_4927548581349126292(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x712db2b017ad696dL, 0x712db2b017ad725cL, "streamExpression")), MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L, 0x108bbd29b4aL, "body"));
  }
  public static SNode sourceNodeQuery_4907898740901061388(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x712db2b017bf4cf0L, 0x712db2b017bf4cf2L, "readerExpression")), MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L, 0x108bbd29b4aL, "body"));
  }
  public static SNode sourceNodeQuery_4907898740901250605(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x441c5be6d4f6bef5L, 0x441c5be6d4f6bf5bL, "filename"));
  }
  public static SNode sourceNodeQuery_6449713081305649196(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x3536540b1e1d20d8L, 0x3536540b1e1d2187L, "fragment"));
  }
  public static SNode sourceNodeQuery_9039864166931224346(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x7744411300250bf8L, 0x774441130028f6a7L, "handlerFunction")), MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L, 0x108bbd29b4aL, "body"));
  }
  public static SNode sourceNodeQuery_224223098167714864(final SourceSubstituteMacroNodeContext _context) {
    return SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c108ca66L, "jetbrains.mps.baseLanguage.structure.ClassConcept"), false, false);
  }
  public static SNode sourceNodeQuery_7518874264089020327(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x1be723a87fb2785eL, 0x1be723a87fc26432L, "reason"));
  }
  public static SNode sourceNodeQuery_7518874264089020773(final SourceSubstituteMacroNodeContext _context) {
    if ((SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x1be723a87fb2785eL, 0x1be723a87fb279a8L, "exception")) != null)) {
      return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x1be723a87fb2785eL, 0x1be723a87fb279a8L, "exception"));
    } else {
      return _quotation_createNode_x583g4_a0a0a0kc();
    }
  }
  public static SNode sourceNodeQuery_7518874264089019492(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x1be723a87fb6cf58L, 0x1be723a87fbcd759L, "message"));
  }
  public static SNode sourceNodeQuery_7507736014961255871(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x6830d620bef9498fL, 0x6830d620bef94990L, "handlerFunction")), MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L, 0x108bbd29b4aL, "body"));
  }
  public static SNode sourceNodeQuery_3941135000200420694(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x36b1b966d2cd1e04L, 0x36b1b966d2cd1ed5L, "expression"));
  }
  public static Object templateArgumentQuery_2477885976695814711(final TemplateArgumentContext _context) {
    return SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c108ca66L, "jetbrains.mps.baseLanguage.structure.ClassConcept"), false, false) != null;
  }
  public static Iterable<SNode> sourceNodesQuery_4927548581349126164(final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x71c4aa344c8b239cL, 0xbd2729caaea770bL, "commands"))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.isInstanceOf(it, MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x712db2b017ad72bcL, "org.campagnelab.NYoSh.structure.GStringCommand")) || SNodeOperations.isInstanceOf(it, MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x440bc6baff9e06b4L, "org.campagnelab.NYoSh.structure.BinaryCommandOperator")) || SNodeOperations.isInstanceOf(it, MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x5ee96c8d4e8af6bcL, "org.campagnelab.NYoSh.structure.ChangeDirectory")) || SNodeOperations.isInstanceOf(it, MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x3536540b1e1d20d8L, "org.campagnelab.NYoSh.structure.BashFragment"));

      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_3834344539456229802(final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x71c4aa344c8b239cL, 0xbd2729caaea770bL, "commands"))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.isInstanceOf(it, MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x712db2b017ad72bcL, "org.campagnelab.NYoSh.structure.GStringCommand")) || SNodeOperations.isInstanceOf(it, MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x440bc6baff9e06b4L, "org.campagnelab.NYoSh.structure.BinaryCommandOperator")) || SNodeOperations.isInstanceOf(it, MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x5ee96c8d4e8af6bcL, "org.campagnelab.NYoSh.structure.ChangeDirectory"));

      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_7507736014961274022(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.collectMany(SModelOperations.roots(_context.getInputModel(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x7744411300250a44L, "org.campagnelab.NYoSh.structure.ErrorManagement")), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x7744411300250a44L, 0x6830d620bef94b11L, "successHandler"));
  }
  public static Iterable<SNode> sourceNodesQuery_9039864166931848938(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.collectMany(SModelOperations.roots(_context.getInputModel(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x7744411300250a44L, "org.campagnelab.NYoSh.structure.ErrorManagement")), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x7744411300250a44L, 0x7744411300250bf6L, "errorHandlers"));
  }
  public static Iterable<SNode> sourceNodesQuery_4236149660851124421(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x7744411300250bf8L, 0x774441130028f6a7L, "handlerFunction")), MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L, 0x108bbd29b4aL, "body")), MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"));
  }
  public static Iterable<SNode> sourceNodesQuery_9039864166930647622(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.collect(SLinkOperations.collectMany(SModelOperations.roots(_context.getInputModel(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x7744411300250a44L, "org.campagnelab.NYoSh.structure.ErrorManagement")), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x7744411300250a44L, 0x7744411300250bf6L, "errorHandlers")), MetaAdapterFactory.getReferenceLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x774441130037b248L, 0x774441130037b249L, "handler"));
  }
  public static Iterable<SNode> sourceNodesQuery_7507736014962008500(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x6830d620bef9498fL, 0x6830d620bef94990L, "handlerFunction")), MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L, 0x108bbd29b4aL, "body")), MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"));
  }
  public static Iterable<SNode> sourceNodesQuery_7507736014962008528(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.collect(SLinkOperations.collectMany(SModelOperations.roots(_context.getInputModel(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x7744411300250a44L, "org.campagnelab.NYoSh.structure.ErrorManagement")), MetaAdapterFactory.getContainmentLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x7744411300250a44L, 0x6830d620bef94b11L, "successHandler")), MetaAdapterFactory.getReferenceLink(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x6830d620bef9499aL, 0x6830d620bef9499bL, "handler"));
  }
  public static SNode weaving_MappingRule_ContextNodeQuery_1428468137065583(final WeavingMappingRuleContext _context) {
    SNode command = ListSequence.fromList(SNodeOperations.getNodeDescendants(_context.getNode(), MetaAdapterFactory.getConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x5132f28e0e080L, "org.campagnelab.NYoSh.structure.IRequireExecuteCommandEnvironment"), false, new SAbstractConcept[]{})).first();
    SNode usage = _context.getOutputNodeByInputNodeAndMappingLabel(command, "usage_executeCommand");
    SNode ancestor = SNodeOperations.getNodeAncestor(usage, MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c108ca66L, "jetbrains.mps.baseLanguage.structure.ClassConcept"), false, true);
    if (ancestor != null) {
      return ancestor;
    }

    SNode outputNode = _context.getCopiedOutputNodeForInputNode(_context.getNode());
    if (outputNode == null) {
      _context.showErrorMessage(_context.getNode(), "Can't find copy of the class concept in the target model");
    }
    return outputNode;
  }
  public static SNode weaving_MappingRule_ContextNodeQuery_3999230645370198099(final WeavingMappingRuleContext _context) {
    SNode stepStatement = ListSequence.fromList(SNodeOperations.getNodeDescendants(_context.getNode(), MetaAdapterFactory.getInterfaceConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x60cbcaafef4d643L, "org.campagnelab.NYoSh.structure.ISomeStepLoggingStatement"), false, new SAbstractConcept[]{})).first();
    SNode usage = _context.getOutputNodeByInputNodeAndMappingLabel(stepStatement, "usage_stepsLogger");
    SNode ancestor = SNodeOperations.getNodeAncestor(usage, MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c108ca66L, "jetbrains.mps.baseLanguage.structure.ClassConcept"), false, true);
    if (ancestor != null) {
      return ancestor;
    }

    SNode outputNode = _context.getCopiedOutputNodeForInputNode(_context.getNode());
    if (outputNode == null) {
      _context.showErrorMessage(_context.getNode(), "Can't find copy of the class concept in the target model");
    }
    return outputNode;
  }
  public static SNode weaving_MappingRule_ContextNodeQuery_7518874264088361608(final WeavingMappingRuleContext _context) {
    SNode stepStatement = ListSequence.fromList(SNodeOperations.getNodeDescendants(_context.getNode(), MetaAdapterFactory.getInterfaceConcept(0xa21a7294c1264f63L, 0x83358fecd8c28c7eL, 0x1be723a87fb27988L, "org.campagnelab.NYoSh.structure.ISomeErrorUsage"), false, new SAbstractConcept[]{})).first();
    SNode usage = _context.getOutputNodeByInputNodeAndMappingLabel(stepStatement, "usage_Errors");
    SNode ancestor = SNodeOperations.getNodeAncestor(usage, MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c108ca66L, "jetbrains.mps.baseLanguage.structure.ClassConcept"), false, true);
    if (ancestor != null) {
      return ancestor;
    }

    SNode outputNode = _context.getCopiedOutputNodeForInputNode(_context.getNode());
    if (outputNode == null) {
      _context.showErrorMessage(_context.getNode(), "Can't find copy of the class concept in the target model");
    }
    return outputNode;
  }
  private final Map<String, ReductionRuleCondition> rrcMethods = new HashMap<String, ReductionRuleCondition>();
  {
    int i = 0;
    rrcMethods.put("4907898740900732084", new QueriesGenerated.RRC(i++));
    rrcMethods.put("4907898740900775118", new QueriesGenerated.RRC(i++));
    rrcMethods.put("4907898740900909781", new QueriesGenerated.RRC(i++));
    rrcMethods.put("4907898740901038181", new QueriesGenerated.RRC(i++));
    rrcMethods.put("4907898740901126699", new QueriesGenerated.RRC(i++));
    rrcMethods.put("2010614965249460527", new QueriesGenerated.RRC(i++));
    rrcMethods.put("2010614965249549321", new QueriesGenerated.RRC(i++));
    rrcMethods.put("2010614965249905422", new QueriesGenerated.RRC(i++));
    rrcMethods.put("2010614965249965972", new QueriesGenerated.RRC(i++));
  }
  @Override
  @NotNull
  public ReductionRuleCondition getReductionRuleCondition(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(rrcMethods.containsKey(id))) {
      return super.getReductionRuleCondition(identity);
    }
    return rrcMethods.get(id);
  }
  private static class RRC implements ReductionRuleCondition {
    private final int methodKey;
    public RRC(int methodKey) {
      this.methodKey = methodKey;
    }
    @Override
    public boolean check(ReductionRuleQueryContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.baseMappingRule_Condition_4907898740900732088(ctx);
        case 1:
          return QueriesGenerated.baseMappingRule_Condition_4907898740900775119(ctx);
        case 2:
          return QueriesGenerated.baseMappingRule_Condition_4907898740900909782(ctx);
        case 3:
          return QueriesGenerated.baseMappingRule_Condition_4907898740901038182(ctx);
        case 4:
          return QueriesGenerated.baseMappingRule_Condition_4907898740901275816(ctx);
        case 5:
          return QueriesGenerated.baseMappingRule_Condition_2010614965249460538(ctx);
        case 6:
          return QueriesGenerated.baseMappingRule_Condition_2010614965249549323(ctx);
        case 7:
          return QueriesGenerated.baseMappingRule_Condition_2010614965249905459(ctx);
        case 8:
          return QueriesGenerated.baseMappingRule_Condition_2010614965249966423(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no condition method for rule %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, CreateRootCondition> crcMethods = new HashMap<String, CreateRootCondition>();
  {
    int i = 0;
    crcMethods.put("2010614965247309602", new QueriesGenerated.CRC(i++));
  }
  @Override
  @NotNull
  public CreateRootCondition getCreateRootRuleCondition(@NotNull QueryKey identity) {
    String id = identity.getTemplateNode().getNodeId().toString();
    if (!(crcMethods.containsKey(id))) {
      return super.getCreateRootRuleCondition(identity);
    }
    return crcMethods.get(id);
  }
  private static class CRC implements CreateRootCondition {
    private final int methodKey;
    public CRC(int methodKey) {
      this.methodKey = methodKey;
    }
    @Override
    public boolean check(@NotNull CreateRootRuleContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.createRootRule_Condition_2010614965247312410(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no condition method for rule %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, QueriesGenerated.WRQ> wrcnMethods = new HashMap<String, QueriesGenerated.WRQ>();
  {
    int i = 0;
    wrcnMethods.put("1428468137065581", new QueriesGenerated.WRQ(i++));
    wrcnMethods.put("3999230645370198097", new QueriesGenerated.WRQ(i++));
    wrcnMethods.put("7518874264088361606", new QueriesGenerated.WRQ(i++));
  }
  @Override
  @NotNull
  public WeaveRuleCondition getWeaveRuleCondition(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(wrcnMethods.containsKey(id))) {
      return super.getWeaveRuleCondition(identity);
    }
    return wrcnMethods.get(id);
  }
  @Override
  @NotNull
  public WeaveRuleQuery getWeaveRuleQuery(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(wrcnMethods.containsKey(id))) {
      return super.getWeaveRuleQuery(identity);
    }
    return wrcnMethods.get(id);
  }
  @NotNull
  @Override
  public WeaveAnchorQuery getWeaveAnchorQuery(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(wrcnMethods.containsKey(id))) {
      return super.getWeaveAnchorQuery(identity);
    }
    return wrcnMethods.get(id);
  }
  private static class WRQ implements WeaveRuleQuery, WeaveRuleCondition, WeaveAnchorQuery {
    private final int methodKey;
    public WRQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @Override
    public boolean check(@NotNull WeavingMappingRuleContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.baseMappingRule_Condition_1428468137067871(ctx);
        case 1:
          return QueriesGenerated.baseMappingRule_Condition_3999230645370603588(ctx);
        case 2:
          return QueriesGenerated.baseMappingRule_Condition_7518874264088361664(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no condition method for rule %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
    @Override
    public SNode contextNode(WeavingMappingRuleContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.weaving_MappingRule_ContextNodeQuery_1428468137065583(ctx);
        case 1:
          return QueriesGenerated.weaving_MappingRule_ContextNodeQuery_3999230645370198099(ctx);
        case 2:
          return QueriesGenerated.weaving_MappingRule_ContextNodeQuery_7518874264088361608(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no context node query method for weaving rule %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }

    }
    @Nullable
    @Override
    public SNode anchorNode(WeavingAnchorContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return null;
        case 1:
          return null;
        case 2:
          return null;
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no anchor query method for rule %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, SourceNodeQuery> snqMethods = new HashMap<String, SourceNodeQuery>();
  {
    int i = 0;
    snqMethods.put("7872582389600940237", new QueriesGenerated.SNQ(i++));
    snqMethods.put("6839116863307682695", new QueriesGenerated.SNQ(i++));
    snqMethods.put("3834344539456361046", new QueriesGenerated.SNQ(i++));
    snqMethods.put("3834344539458185979", new QueriesGenerated.SNQ(i++));
    snqMethods.put("435930706556388982", new QueriesGenerated.SNQ(i++));
    snqMethods.put("435930706556389034", new QueriesGenerated.SNQ(i++));
    snqMethods.put("3834344539456372649", new QueriesGenerated.SNQ(i++));
    snqMethods.put("435930706556389179", new QueriesGenerated.SNQ(i++));
    snqMethods.put("3834344539457451313", new QueriesGenerated.SNQ(i++));
    snqMethods.put("3834344539457522265", new QueriesGenerated.SNQ(i++));
    snqMethods.put("4907898740900748877", new QueriesGenerated.SNQ(i++));
    snqMethods.put("4927548581349126362", new QueriesGenerated.SNQ(i++));
    snqMethods.put("4927548581349126292", new QueriesGenerated.SNQ(i++));
    snqMethods.put("4907898740901061388", new QueriesGenerated.SNQ(i++));
    snqMethods.put("4907898740901250605", new QueriesGenerated.SNQ(i++));
    snqMethods.put("6449713081305649196", new QueriesGenerated.SNQ(i++));
    snqMethods.put("9039864166931224346", new QueriesGenerated.SNQ(i++));
    snqMethods.put("224223098167714864", new QueriesGenerated.SNQ(i++));
    snqMethods.put("7518874264089020327", new QueriesGenerated.SNQ(i++));
    snqMethods.put("7518874264089020773", new QueriesGenerated.SNQ(i++));
    snqMethods.put("7518874264089019492", new QueriesGenerated.SNQ(i++));
    snqMethods.put("7507736014961255871", new QueriesGenerated.SNQ(i++));
    snqMethods.put("3941135000200420694", new QueriesGenerated.SNQ(i++));
  }
  @NotNull
  @Override
  public SourceNodeQuery getSourceNodeQuery(@NotNull QueryKey identity) {
    final String id = ((QueryKeyImpl) identity).getQueryNodeId().toString();
    if (!(snqMethods.containsKey(id))) {
      return super.getSourceNodeQuery(identity);
    }
    return snqMethods.get(id);
  }
  private static class SNQ implements SourceNodeQuery {
    private final int methodKey;
    public SNQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @Nullable
    public SNode evaluate(@NotNull SourceSubstituteMacroNodeContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.sourceNodeQuery_7872582389600940237(ctx);
        case 1:
          return QueriesGenerated.sourceNodeQuery_6839116863307682695(ctx);
        case 2:
          return QueriesGenerated.sourceNodeQuery_3834344539456361046(ctx);
        case 3:
          return QueriesGenerated.sourceNodeQuery_3834344539458185979(ctx);
        case 4:
          return QueriesGenerated.sourceNodeQuery_435930706556388982(ctx);
        case 5:
          return QueriesGenerated.sourceNodeQuery_435930706556389034(ctx);
        case 6:
          return QueriesGenerated.sourceNodeQuery_3834344539456372649(ctx);
        case 7:
          return QueriesGenerated.sourceNodeQuery_435930706556389179(ctx);
        case 8:
          return QueriesGenerated.sourceNodeQuery_3834344539457451313(ctx);
        case 9:
          return QueriesGenerated.sourceNodeQuery_3834344539457522265(ctx);
        case 10:
          return QueriesGenerated.sourceNodeQuery_4907898740900748877(ctx);
        case 11:
          return QueriesGenerated.sourceNodeQuery_4927548581349126362(ctx);
        case 12:
          return QueriesGenerated.sourceNodeQuery_4927548581349126292(ctx);
        case 13:
          return QueriesGenerated.sourceNodeQuery_4907898740901061388(ctx);
        case 14:
          return QueriesGenerated.sourceNodeQuery_4907898740901250605(ctx);
        case 15:
          return QueriesGenerated.sourceNodeQuery_6449713081305649196(ctx);
        case 16:
          return QueriesGenerated.sourceNodeQuery_9039864166931224346(ctx);
        case 17:
          return QueriesGenerated.sourceNodeQuery_224223098167714864(ctx);
        case 18:
          return QueriesGenerated.sourceNodeQuery_7518874264089020327(ctx);
        case 19:
          return QueriesGenerated.sourceNodeQuery_7518874264089020773(ctx);
        case 20:
          return QueriesGenerated.sourceNodeQuery_7518874264089019492(ctx);
        case 21:
          return QueriesGenerated.sourceNodeQuery_7507736014961255871(ctx);
        case 22:
          return QueriesGenerated.sourceNodeQuery_3941135000200420694(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, SourceNodesQuery> snsqMethods = new HashMap<String, SourceNodesQuery>();
  {
    int i = 0;
    snsqMethods.put("4927548581349126164", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("3834344539456229802", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("7507736014961274022", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("9039864166931848938", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("4236149660851124421", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("9039864166930647622", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("7507736014962008500", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("7507736014962008528", new QueriesGenerated.SNsQ(i++));
  }
  @NotNull
  @Override
  public SourceNodesQuery getSourceNodesQuery(@NotNull QueryKey identity) {
    final String id = ((QueryKeyImpl) identity).getQueryNodeId().toString();
    if (!(snsqMethods.containsKey(id))) {
      return super.getSourceNodesQuery(identity);
    }
    return snsqMethods.get(id);
  }
  private static class SNsQ implements SourceNodesQuery {
    private final int methodKey;
    public SNsQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @NotNull
    public Collection<SNode> evaluate(@NotNull SourceSubstituteMacroNodesContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4927548581349126164(ctx));
        case 1:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_3834344539456229802(ctx));
        case 2:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_7507736014961274022(ctx));
        case 3:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_9039864166931848938(ctx));
        case 4:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4236149660851124421(ctx));
        case 5:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_9039864166930647622(ctx));
        case 6:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_7507736014962008500(ctx));
        case 7:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_7507736014962008528(ctx));
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, PropertyValueQuery> pvqMethods = new HashMap<String, PropertyValueQuery>();
  {
    int i = 0;
    pvqMethods.put("7872582389600940397", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "operator"));
    pvqMethods.put("435930706556389110", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "description"));
    pvqMethods.put("435930706556389137", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "_logSuccess"));
    pvqMethods.put("435930706556389154", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "description"));
    pvqMethods.put("435930706556389161", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "_logReason"));
    pvqMethods.put("5787209143228212927", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "exception"));
    pvqMethods.put("9039864166930640539", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "reduceErrorHandler"));
    pvqMethods.put("7507736014962008516", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "reduceSuccessHandler"));
    pvqMethods.put("9039864166930247300", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "reduceErrorHandler"));
    pvqMethods.put("7507736014961255883", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "reduceErrorHandler"));
    pvqMethods.put("731554740236414149", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "lastExitCode2"));
    pvqMethods.put("731554740236377046", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "lastExitCode1"));
  }
  @NotNull
  @Override
  public PropertyValueQuery getPropertyValueQuery(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(pvqMethods.containsKey(id))) {
      return super.getPropertyValueQuery(identity);
    }
    return pvqMethods.get(id);
  }
  private static class PVQ extends PropertyValueQuery.Base {
    private final int methodKey;
    /*package*/ PVQ(int methodKey, SProperty property, String templateValue) {
      super(property, templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull PropertyMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.propertyMacro_GetPropertyValue_7872582389600940400(ctx);
        case 1:
          return QueriesGenerated.propertyMacro_GetPropertyValue_435930706556389111(ctx);
        case 2:
          return QueriesGenerated.propertyMacro_GetPropertyValue_435930706556389138(ctx);
        case 3:
          return QueriesGenerated.propertyMacro_GetPropertyValue_435930706556389155(ctx);
        case 4:
          return QueriesGenerated.propertyMacro_GetPropertyValue_435930706556389162(ctx);
        case 5:
          return QueriesGenerated.propertyMacro_GetPropertyValue_5787209143228213122(ctx);
        case 6:
          return QueriesGenerated.propertyMacro_GetPropertyValue_9039864166930640540(ctx);
        case 7:
          return QueriesGenerated.propertyMacro_GetPropertyValue_7507736014962008517(ctx);
        case 8:
          return QueriesGenerated.propertyMacro_GetPropertyValue_9039864166930247303(ctx);
        case 9:
          return QueriesGenerated.propertyMacro_GetPropertyValue_7507736014961255884(ctx);
        case 10:
          return QueriesGenerated.propertyMacro_GetPropertyValue_731554740236414150(ctx);
        case 11:
          return QueriesGenerated.propertyMacro_GetPropertyValue_731554740236377473(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, IfMacroCondition> imcMethods = new HashMap<String, IfMacroCondition>();
  {
    int i = 0;
    imcMethods.put("7414196263098247786", new QueriesGenerated.IfMC(i++));
    imcMethods.put("5949986731306071702", new QueriesGenerated.IfMC(i++));
    imcMethods.put("4325409482886268089", new QueriesGenerated.IfMC(i++));
    imcMethods.put("7855977029128093195", new QueriesGenerated.IfMC(i++));
    imcMethods.put("9138295635397069270", new QueriesGenerated.IfMC(i++));
    imcMethods.put("435930706556389240", new QueriesGenerated.IfMC(i++));
    imcMethods.put("2477885976697156502", new QueriesGenerated.IfMC(i++));
  }
  @NotNull
  @Override
  public IfMacroCondition getIfMacroCondition(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(imcMethods.containsKey(id))) {
      return super.getIfMacroCondition(identity);
    }
    return imcMethods.get(id);
  }
  private static class IfMC implements IfMacroCondition {
    private final int methodKey;
    public IfMC(int methodKey) {
      this.methodKey = methodKey;
    }
    @Override
    public boolean check(@NotNull IfMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.ifMacro_Condition_7414196263098247788(ctx);
        case 1:
          return QueriesGenerated.ifMacro_Condition_5949986731306071704(ctx);
        case 2:
          return QueriesGenerated.ifMacro_Condition_4325409482886268091(ctx);
        case 3:
          return QueriesGenerated.ifMacro_Condition_7855977029128093197(ctx);
        case 4:
          return QueriesGenerated.ifMacro_Condition_9138295635397069272(ctx);
        case 5:
          return QueriesGenerated.ifMacro_Condition_435930706556389241(ctx);
        case 6:
          return QueriesGenerated.ifMacro_Condition_2477885976697156505(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no condition method for if macro %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, ReferenceTargetQuery> rtqMethods = new HashMap<String, ReferenceTargetQuery>();
  {
    rtqMethods.put("4927548581349126140", new QueriesGenerated.RTQ(0, "appendCommand"));
    rtqMethods.put("7414196263097490722", new QueriesGenerated.RTQ(1, "variableDestination"));
    rtqMethods.put("9213669739149152105", new QueriesGenerated.RTQ(2, "fail"));
    rtqMethods.put("9039864166929501703", new QueriesGenerated.RTQ(3, "fail"));
    rtqMethods.put("9039864166928527665", new QueriesGenerated.RTQ(4, "done"));
    rtqMethods.put("4907898740901298344", new QueriesGenerated.RTQ(5, "consumeStandardOutput"));
    rtqMethods.put("7507736014961274011", new QueriesGenerated.RTQ(6, "reduceSuccessHandler"));
    rtqMethods.put("9039864166931916242", new QueriesGenerated.RTQ(7, "reduceErrorHandler"));
    rtqMethods.put("9039864166931122957", new QueriesGenerated.RTQ(8, "reducedErrorHandler"));
    rtqMethods.put("7507736014961225986", new QueriesGenerated.RTQ(9, "reducedSuccessHandler"));
  }
  @NotNull
  @Override
  public ReferenceTargetQuery getReferenceTargetQuery(@NotNull QueryKey queryKey) {
    final String id = queryKey.getTemplateNode().getNodeId().toString();
    if (!(rtqMethods.containsKey(id))) {
      return super.getReferenceTargetQuery(queryKey);
    }
    return rtqMethods.get(id);
  }
  private static class RTQ extends ReferenceTargetQuery.Base {
    private final int methodKey;
    /*package*/ RTQ(int methodKey, String templateValue) {
      super(templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull ReferenceMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.referenceMacro_GetReferent_4927548581349126141(ctx);
        case 1:
          return QueriesGenerated.referenceMacro_GetReferent_7414196263097490723(ctx);
        case 2:
          return QueriesGenerated.referenceMacro_GetReferent_9213669739149152106(ctx);
        case 3:
          return QueriesGenerated.referenceMacro_GetReferent_9039864166929501704(ctx);
        case 4:
          return QueriesGenerated.referenceMacro_GetReferent_9039864166928527666(ctx);
        case 5:
          return QueriesGenerated.referenceMacro_GetReferent_4907898740901298345(ctx);
        case 6:
          return QueriesGenerated.referenceMacro_GetReferent_7507736014961274012(ctx);
        case 7:
          return QueriesGenerated.referenceMacro_GetReferent_9039864166931916245(ctx);
        case 8:
          return QueriesGenerated.referenceMacro_GetReferent_9039864166931122960(ctx);
        case 9:
          return QueriesGenerated.referenceMacro_GetReferent_7507736014961225987(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, CallArgumentQuery> caqMethods = new HashMap<String, CallArgumentQuery>();
  {
    caqMethods.put("2477885976695814709", new QueriesGenerated.CAQ(0));
  }
  @NotNull
  @Override
  public CallArgumentQuery getTemplateCallArgumentQuery(@NotNull QueryKey queryKey) {
    final String id = queryKey.getTemplateNode().getNodeId().toString();
    if (!(caqMethods.containsKey(id))) {
      return super.getTemplateCallArgumentQuery(queryKey);
    }
    return caqMethods.get(id);
  }
  private static class CAQ implements CallArgumentQuery {
    private final int methodKey;
    /*package*/ CAQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull TemplateArgumentContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.templateArgumentQuery_2477885976695814711(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private static SNode _quotation_createNode_x583g4_a0a0a0kc() {
    PersistenceFacade facade = PersistenceFacade.getInstance();
    SNode quotedNode_1 = null;
    quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf940cd6167L, "NullLiteral"), null, null, false);
    return quotedNode_1;
  }
}
